### ISSUE TITLE
Not working on Z1 with newest firmware?

### ISSUE THREAD

**Issue by KieranJDuncan** [ricohapi/theta-plugins#1]
I updated my Z1 camera firmware to 2.30.1 and I can't install several plugins which should be supported on the Z1 (Dual Fisheye RAW, or HDRI for example). When trying to install, the Ricoh Theta software says the plugins are not supported on this camera model. 

Is there a solution for this? 

Thanks!

**Comment by DaisukeHohjoh** [comment]
@KieranJDuncan 
Did you solve this issue or still have this issue ?

**Comment by DaisukeHohjoh** [comment]
Sorry for letting me close this Issue ticket, please issue another one if you still see a problem.
