### ISSUE TITLE
AE Bracketing vs DFE plugin?

### ISSUE THREAD

**Issue by GeorgeThetaZ1** [ricohapi/theta-plugins#15]
Hi! Can someone tell me if there is a big quality difference between AE Bracketιng and Dualfisheye plugin?
I Know that DFE is just faster than AE Bracket. I see there is more control in AE Bracket than DFE. (concerning the EV steps)
So what are the advantages of DFE over AE Bracket.
I have my first virtual tour this week and I dont know what to use.
I want 5 to 7 dng's so I go to bracket. I dont want HDR rendering. 
Concerning image quality. What would you choose AE Bracketing or DFE plugin?
Thank you

**Comment by DaisukeHohjoh** [comment]
Hi,

Image quality should be almost same.
Speaking of details, I think there are two gaps between DFE plugin and AE Bracketing.

1. DFE sets to ISO64 less noise than ISO80, but it is not official supported setting (=it is not actual ISO64). You can refer to this post as well.  https://github.com/ricohapi/theta-plugins/issues/11
2. AE Bracketing has a little more heat noise especially for long exposure use-case, such as 10 seconds per shot. Some enthusiastic Z1 users have reported this phenomenon in Facebook Group. https://www.facebook.com/groups/ricohtheta360community/permalink/820057999274253/

DFE
- Image quality is a little more stable than AE Bracketing, by above two reasons.

AE Bracketing
- Much faster capturing & image processing than DFE.
- More exposure controlling.
- Can check light condition, etc. with live-preview image by Ricoh smartphone app, before capturing.

Best regards,
Daisuke Hohjoh

**Comment by GeorgeThetaZ1** [comment]
Thank you so much for the reply.
