### ISSUE TITLE
color space of EXR files from HDRI plugin

### ISSUE THREAD

**Issue by Threedio** [ricohapi/theta-plugins#19]
Greetings,

I'm trying to find out the color space of the EXR files produced by the HDRI addon.  Browsing various articles online I have seen it said that it is Linear Rec.2020, Linear Rec.709 and sRGB.  What is the true answer?  PS Thanks for a great plugin!

**Comment by DaisukeHohjoh** [comment]
@ken1roh 
Could you provide answer to the customer ?

**Comment by ken1roh** [comment]
@Threedio
The color space for EXRs generated by the HDRI Plugin is sRGB.

The color space of the EXR depends on how it is generated.
For example, if the response argument (camera response function) is specified in OpenCV's cv2.createMergeDebevec, the generated EXR color space will be Linear RGB.
