### ISSUE TITLE
Cannot install to Theta x

### ISSUE THREAD

**Issue by LiangHuangBC** [ricohapi/theta-plugins#7]
There is no way to install plugin into Theta X. From May 2023, in device store is removed, and there no desktop app anymore. Tried mobile app on Iphone, can not open the link provided on the github :"https://link.ricoh360.com/plugins/com.theta360.cloudstreaming/apk", and also no apk download link provided. 

Can anybody provide a apk directly?

**Comment by DaisukeHohjoh** [comment]
@LiangHuangBC 
I am sorry for your inconvenience. 

Regarding desktop app, the link is still active but very hard to find it in our new website now.

- [Windows](https://support.theta360.com/intl/download/pcapp/windows)
- [Mac](https://support.theta360.com/intl/download/pcapp/macosx)

Then you can install Wireless LIVE Streaming plugin with the link provided on the GitHub : "https://link.ricoh360.com/plugins/com.theta360.cloudstreaming/apk".

---

By the way, RICOH is releasing apk officially in following repository. You can refer it too.
https://github.com/ricohapi/theta-wireless-live-streaming-plugin/releases/tag/v1.2.3

Best regards,
Daisuke Hohjoh

**Comment by SystemR** [comment]
Any chance getting the apk for this one?

https://github.com/ricohapi/theta-vr-media-connection-plugin

cloudstreaming apk link is still dead

**Comment by DaisukeHohjoh** [comment]
@SystemR 
Sorry for your confusion. THETA Plugin Store have been moved to [GitHub](https://github.com/ricohapi/theta-plugins/tree/main).

You can install VR Media Connection plugin via following website.
https://github.com/ricohapi/theta-plugins/tree/main/plugins/com.theta360.vrmediaconnection

Click `Install on THETA` button, then launch PC/Mac THETA app and start plugin installation.

Also, Wireless LIVE Streaming plugin is here.
https://github.com/ricohapi/theta-plugins/tree/main/plugins/com.theta360.cloudstreaming

**Comment by SystemR** [comment]
Hey! Thanks,

I'm now able to install plugins. That instruction should be listed on the README.md. 

Prior to installing RICOH THETA app, clicking on the `Install on THETA` button doesn't do anything which caused the confusion.

Thanks!

**Comment by DaisukeHohjoh** [comment]
@SystemR 

> That instruction should be listed on the README.md.

Thank you for feedback kindly. Yes, RICOH will consider to add more detailed instruction in this repository.

**Comment by DaisukeHohjoh** [comment]
https://github.com/ricohapi/theta-plugins/commit/e2f94a14ae2c2705d8915cbabf8623b6a022ddec
RICOH updated README.md for more detailed instruction to install plugins.
