### ISSUE TITLE
How to change to mode

### ISSUE THREAD

**Issue by PawelBialowas81** [ricohapi/theta-plugins#9]
Hi
I’m having a huge problem with changeing the mode from burst to bracket. I’m there a more detailed descryption on how to do it?

**Comment by DaisukeHohjoh** [comment]
Hi @PawelBialowas81 ,

> changeing the mode from burst to bracket

Did you ask about [DualFisheye Plugin](https://github.com/ricohapi/theta-plugins/tree/main/plugins/com.hirota41.dualfisheye_plugin) or [DualFisheye RAW Plugin](https://github.com/ricohapi/theta-plugins/tree/main/plugins/com.hirota41.dualfisheye_plugin2) for Theta Z1 ?

If my guess is correct, following picture explains how to change the mode.
https://github.com/ricohapi/theta-plugins/blob/main/plugins/com.hirota41.dualfisheye_plugin2/2.png

Best regards,
Daisuke Hohjoh

**Comment by PawelBialowas81** [comment]
Hi, 
First of all my appolagies.. It was late.. I'm testing few plugins at the same time.  I don't know why it end up in DualFishey plugin. 
My question was to the "HDRI" plugin.
Sorry for the mistke (first time using github)
Best regards,
Pawel Bialowas

**Comment by ken1roh** [comment]
Hi @PawelBialowas81,
Switching between bracket mode and burst mode can be done using "RICOH THETA" basic app for the smartphone.
The procedure is as follows

1. Connect Theta Z1 to your smartphone via wireless LAN.
For more information on connecting to a smartphone, please refer to
[https://support.theta360.com/en/manual/z1/content/prepare/prepare_06.html](https://support.theta360.com/en/manual/z1/content/prepare/prepare_06.html)
2. Set "HDRI" as an active plug-in from "Settings" - "Camera settings"- "Plug-in” in "RICOH THETA" basic app for the smartphone.
The browser is launched and the live preview is displayed.
3. Tap the gear icon in the upper right corner of the Live View screen.
The shooting settings screen will be displayed.
4. Burst capture mode is set to ON or OFF.
When set to OFF, the camera will be in bracketing mode.

**Comment by PawelBialowas81** [comment]
@ken1roh 
Hi!
Thank you !
Works Llike a charm!
All the best!
